npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "8622F8D8-8F56-4096-8A1D-EC8EE37C793A"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "8622F8D8-8F56-4096-8A1D-EC8EE37C793A"